name: 📁 Sync Files

on:
  push:
    branches:
      - main

jobs:
  sync-files:
    name: 🔄 Sync Files
    runs-on: ubuntu-22.04
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v3
      - name: 📁 Synchronization
        uses: BetaHuhn/repo-file-sync-action@v1.21.0
        with:
          GH_PAT: ${{ secrets.GH_FULL_PAT }}
          COMMIT_PREFIX: "chore:"
          ORIGINAL_MESSAGE: true
          COMMIT_EACH_FILE: false
          SKIP_PR: true
          GIT_USERNAME: phnx47[bot]
          GIT_EMAIL: 78849906+phnx47-bot@users.noreply.github.com
